dependencies:
  - python=3.8
  - pip:
      # Protobuf is needed to avoid conflict with managed spark.
      - protobuf==3.19.6
      # For asynchronous HTTP requests
      - aiohttp==3.8.4
      # Online feature store core SDK
      - azureml-featurestore[online]==1.1.1
      - azure-ai-ml==1.24.0
      # Azure management libraries.
      - azure-mgmt-msi
      - azure-mgmt-redis
      - azure-mgmt-authorization==3.0.0
      # Required for working with observation data in online feature set samples.
      - pandas==1.5.3
      - scikit-learn
      - azureml-inference-server-http
      # Required for working azure cli.
      - azure-cli
name: fs_online_env